In [1]:
# Import required libraries
import numpy as np
import pandas as pd

# Import Iris dataset
from sklearn.datasets import load_iris

# Split dataset into training and testing data
from sklearn.model_selection import train_test_split

# KNN Classification model
from sklearn.neighbors import KNeighborsClassifier

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# -----------------------------
# KNN CLASSIFICATION
# -----------------------------

# Load Iris dataset
iris = load_iris()

# Features (input data)
X = iris.data

# Target labels (flower species)
y = iris.target

# Split dataset:
# 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Number of nearest neighbors
k = 3

# Create KNN classifier model
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Train the model
knn_classifier.fit(X_train, y_train)

# Predict output for test data
y_pred = knn_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print accuracy
print(f'Accuracy: {accuracy:.2f}')

# Print confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print detailed classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))


# ==========================================================
# KNN REGRESSION
# ==========================================================

# Generate sample regression dataset
from sklearn.datasets import make_regression

# Import train-test split again
from sklearn.model_selection import train_test_split

# KNN Regression model
from sklearn.neighbors import KNeighborsRegressor

# Regression evaluation metrics
from sklearn.metrics import mean_squared_error, r2_score


# Create synthetic dataset
# 200 samples
# 2 input features
# noise=10 adds randomness
X, y = make_regression(
    n_samples=200,
    n_features=2,
    noise=10
)

# Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2
)

# Create KNN Regressor model
# Uses 5 nearest neighbors
model = KNeighborsRegressor(n_neighbors=5)

# Train the model
model.fit(X_train, y_train)

# Predict values for test data
y_pred = model.predict(X_test)

# Calculate Mean Squared Error
mse = mean_squared_error(y_test, y_pred)

# Calculate R² Score
r2 = r2_score(y_test, y_pred)

# Print evaluation results
print("Mean Squared Error:", mse)
print("R² Score:", r2)

Accuracy: 1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Mean Squared Error: 655.0507449870327
R² Score: 0.9265693249077348
